trigger:
  batch: true
  branches:
    include:
      - "master"

variables:
  - name: SolutionBaseName
    value: SFA.DAS.ContentApi
  - name: buildConfiguration
    value: release
  - group: RELEASE Management Resources
  - group: RELEASE das-content-api

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/2.1.26
    endpoint: SkillsFundingAgency
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/5.1.8
    endpoint: SkillsFundingAgency
  pipelines:
  - pipeline: das-employer-config
    project: Digital Apprenticeship Service
    source: das-employer-config
    branch: master

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml
    parameters:
      SolutionBaseName: $(SolutionBaseName)
      BuildConfiguration: $(BuildConfiguration)
  - template: azure-pipelines-templates/build/job/dacpac-template.yml@das-platform-building-blocks
    parameters:
      SolutionBaseName: $(SolutionBaseName).dacpac
      SqlProjectPath: src/$(SolutionBaseName).Database/$(SolutionBaseName).Database.sqlproj

- stage: Deploy_AT
  dependsOn: Build
  displayName: Deploy to AT
  condition: and(succeeded(), eq(variables.Deploy, 'true'))
  variables:
  - group: DevTest Management Resources
  - group: AT DevTest Shared Resources
  - group: AT das-content-api
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      Environment: AT
      ServiceConnection: SFA-DAS-DevTest-ARM
      SolutionBaseName: $(SolutionBaseName)
      AppRoleAssignmentsServiceConnection: das-app-role-assignments-CDS
